# Generated by Django 4.1.1 on 2023-02-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=30)),
                ('Categoria', models.CharField(max_length=30)),
                ('Pais', models.CharField(max_length=30)),
                ('Lenguaje', models.CharField(max_length=30)),
                ('Director', models.CharField(max_length=30)),
                ('Sinopsis', models.CharField(max_length=30)),
                ('Duracion', models.CharField(max_length=30)),
                ('Caratula', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Puestos', models.CharField(max_length=30)),
                ('pantalla', models.CharField(max_length=30)),
                ('Nombre', models.CharField(max_length=30)),
            ],
        ),
    ]
